using Dapper.Contrib.Extensions;
using System;

namespace P21_latest_template.Entities
{
    [Table("company")]
    public class Company
    {
        [ExplicitKey]
        public string company_id { get; set; }
        public string company_name { get; set; }
        public string federal_id_no { get; set; }
        public string fiscal_year_end { get; set; }
        public DateTime date_created { get; set; }
        public DateTime date_last_modified { get; set; }
        public string last_maintained_by { get; set; }
        public decimal address_id { get; set; }
        public string delete_flag { get; set; }
        public string re_price_line_items { get; set; }
        public string pricing_by_location { get; set; }
        public string gl_account_length { get; set; }
        public string gl_capitalized_overhead { get; set; }
        public string gl_freight_in { get; set; }
        public decimal? number_of_periods { get; set; }
        public string retained_earnings_acct_no { get; set; }
        public string terms_taken_account_no { get; set; }
        public decimal home_currency_id { get; set; }
        public string gl_gain_or_loss_acct { get; set; }
        public string san { get; set; }
        public string group_control_no { get; set; }
        public string intl_san { get; set; }
        public string gst_paid_acct { get; set; }
        public decimal? max_invoice_allowance { get; set; }
        public string gst_registration_no { get; set; }
        public string stage_clearing_account_no { get; set; }
        public string transmitter_control_code { get; set; }
        public string foreign_entity_indicator { get; set; }
        public string use_branch_accounting { get; set; }
        public decimal? branch_segment_in_coa { get; set; }
        public decimal? inv_scan_1 { get; set; }
        public decimal? inv_scan_2 { get; set; }
        public decimal? inv_scan_3 { get; set; }
        public decimal? inv_scan_4 { get; set; }
        public decimal? inv_scan_5 { get; set; }
        public decimal? inv_scan_6 { get; set; }
        public decimal? ar_aging_period1 { get; set; }
        public decimal? ar_aging_period2 { get; set; }
        public decimal? ar_aging_period3 { get; set; }
        public string jc_flag { get; set; }
        public string inv_receipts_clearing_acct { get; set; }
        public string interbranch_rec_payable_acct { get; set; }
        public string branch_debit_equal_credit { get; set; }
        public decimal? fc_percentage { get; set; }
        public decimal? fc_grace_days { get; set; }
        public decimal? minimum_fc { get; set; }
        public decimal? minimum_fc_to_invoice { get; set; }
        public string wip_cos_account_number { get; set; }
        public string compound_fc { get; set; }
        public string fc_allowed_acct { get; set; }
        public string fc_invoice_class { get; set; }
        public string generate_finance_charges { get; set; }
        public string fc_allowed_account { get; set; }
        public string fc_revenue_account { get; set; }
        public string using_encumbrances { get; set; }
        public decimal? cost_to_order { get; set; }
        public decimal? carrying_cost { get; set; }
        public decimal? unit_cost { get; set; }
        public string track_ap_by_branch { get; set; }
        public string track_ar_by_branch { get; set; }
        public string track_prod_capitalized_oh { get; set; }
        public string logo_path_filename { get; set; }
        public string commission_expense_acct { get; set; }
        public string accrual_acct { get; set; }
        public string inv_cost_variance_acct { get; set; }
        public string inv_freight_variance_acct { get; set; }
        public string inv_qty_variance_acct { get; set; }
        public string post_variance_to_avg_cost { get; set; }
        public string prorate_freight { get; set; }
        public string post_freight_to_avg_cost { get; set; }
        public string frl_use_frx { get; set; }
        public string frl_acct_mask { get; set; }
        public int? frl_number_of_segments { get; set; }
        public int? frl_natural_segment { get; set; }
        public string create_order_based_transfers { get; set; }
        public string mark_up_on_transfers { get; set; }
        public string mark_up_type { get; set; }
        public decimal? mark_up_value { get; set; }
        public string source_mark_up_account { get; set; }
        public string mark_up_source { get; set; }
        public string source_other_charge_account { get; set; }
        public string destination_mark_up_acct { get; set; }
        public string destination_other_charge_acct { get; set; }
        public DateTime frl_last_transfer_date { get; set; }
        public int? default_source_price_cd { get; set; }
        public decimal? default_multiplier { get; set; }
        public string landed_cost_clearing_acct { get; set; }
        public int? frl_max_batch_id { get; set; }
        public decimal? default_sales_location_id { get; set; }
        public string edi_export_path { get; set; }
        public int? freight_code_uid { get; set; }
        public short number_of_demand_periods { get; set; }
        public string inv_freight_expense_acct { get; set; }
        public string requisition_clearing_acct { get; set; }
        public string restocking_fee_account_no { get; set; }
        public string signature_path { get; set; }
        public string lot_cost_change_account_no { get; set; }
        public string rebate_account_no { get; set; }
        public string rebate_allowance_account_no { get; set; }
        public string allow_discounts_on_partial_pmt { get; set; }
        public string auto_apply_avail_discounts { get; set; }
        public int grace_period_days { get; set; }
        public string disassembly_reason_id { get; set; }
        public string tpcx_member { get; set; }
        public string vendor_consign_inv_offset_acct { get; set; }
        public int finance_chg_inv_due_date_code { get; set; }
        public string rma_receipt_clearing_acct { get; set; }
        public string rma_adjustment_reason_id { get; set; }
        public decimal? rma_default_rts_location_id { get; set; }
        public string rma_auto_return_to_stock { get; set; }
        public string inventory_adjustment_reason_id { get; set; }
        public string returned_check_fee_acct { get; set; }
        public decimal? allowable_invoice_variance { get; set; }
        public string invoice_variance_type_flag { get; set; }
        public string create_prepaid_invoice_flag { get; set; }
        public string tag_suffix { get; set; }
        public int? data_identifier_group_uid { get; set; }
        public string rf_scanner_prefix { get; set; }
        public decimal? default_arpymt_bank_no { get; set; }
        public string default_arpymt_branch_id { get; set; }
        public string carrier_insurance_acct { get; set; }
        public string post_lc_variance_to_avg_cost { get; set; }
        public decimal restock_fee_percentage { get; set; }
        public string restock_fee_account { get; set; }
        public string coupon_clearing_acct_no { get; set; }
        public string disassembly_cost_var_acct_no { get; set; }
        public string coupon_issued_acct_no { get; set; }
        public string job_id_required_flag { get; set; }
        public string track_lost_sales_flag { get; set; }
        public string restocking_fee_taxable_flag { get; set; }
        public string company_mac_rounding_acct { get; set; }
        public string special_inventory_acct { get; set; }
        public string inv_in_vessel_acct { get; set; }
        public string inv_in_transit_clearing_acct { get; set; }
        public string commission_receivable_acct { get; set; }
        public string commission_revenue_acct { get; set; }
        public string commission_allowance_acct { get; set; }
        public string lot_bill_clearing_acct { get; set; }
        public string assembly_variance_acct { get; set; }
        public string gl_acct_for_applied_labor { get; set; }
        public string gl_acct_for_labor_cos { get; set; }
        public string gl_acct_for_freight_clearing { get; set; }
        public string currency_bank_clearing_acct { get; set; }
        public string assembly_cost_variance_acct { get; set; }
        public string post_commission_accruals_flag { get; set; }
        public string ups_account_no { get; set; }
        public string ups_olt_user_id { get; set; }
        public string ups_olt_password { get; set; }
        public string ups_olt_access_key { get; set; }
        public string duns_no { get; set; }
        public int? default_fax_cover_uid { get; set; }
        public int? predefined_coa_cd { get; set; }
        public string gl_acct_longterm_contracts { get; set; }
        public string sp_alloc_from_stock_var_acct { get; set; }
        public string gl_acct_for_labor_wip { get; set; }
        public string prod_auto_transfer_reason_id { get; set; }
        public string coupon_allowed_acct_no { get; set; }
        public string accept_pymts_with_no_inv_flag { get; set; }
        public string accept_incorrect_inv_flag { get; set; }
        public string accept_partial_payment_flag { get; set; }
        public string pedigree_contact_id { get; set; }
        public string validate_commission_split_flag { get; set; }
        public string duns_number { get; set; }
        public short? branch_start { get; set; }
        public short? branch_length { get; set; }
        public short? account_length { get; set; }
        public string vertex_enabled { get; set; }
        public string default_sales_tax_payable_acct { get; set; }
        public string pall_rep_number { get; set; }
        public string intrastat_enabled_flag { get; set; }
        public string use_int_address_format_flag { get; set; }
        public string use_cogs_acct_for_oci_flag { get; set; }
        public string restocking_fee_id { get; set; }
        public string use_quote_revision_flag { get; set; }
        public string summary_commodity_code { get; set; }
        public string company_taxgroup_by_zipcode_flag { get; set; }
        public string service_user_number { get; set; }
        public string cfn_cost_goods_sold_acct { get; set; }
        public string cfn_receivable_acct { get; set; }
        public string cfn_revenue_acct { get; set; }
        public string round_unit_prices_flag { get; set; }
        public string iva_enabled { get; set; }
        public string track_inv_on_water_branch_flag { get; set; }
        public string freight_wip_acct { get; set; }
        public string avalara_enabled { get; set; }
        public string pending_warranty_acct { get; set; }
        public string default_customer_tax_class { get; set; }
    }
}
