using Dapper.Contrib.Extensions;
using System;

namespace P21_latest_template.Entities
{
    [Table("customer")]
    public class Customer
    {
        [ExplicitKey]
        public decimal customer_id { get; set; }
        [ExplicitKey]
        public string company_id { get; set; }
        public string taxable_flag { get; set; }
        public string resale_certificate { get; set; }
        public decimal? credit_limit { get; set; }
        public decimal? credit_limit_used { get; set; }
        public string terms_id { get; set; }
        public string salesrep_id { get; set; }
        public string ar_account_no { get; set; }
        public string revenue_account_no { get; set; }
        public string cos_account_no { get; set; }
        public string allowed_account_no { get; set; }
        public string terms_account_no { get; set; }
        public string delete_flag { get; set; }
        public DateTime date_created { get; set; }
        public DateTime date_last_modified { get; set; }
        public string last_maintained_by { get; set; }
        public string customer_id_string { get; set; }
        public string freight_account_no { get; set; }
        public string brokerage_account_no { get; set; }
        public string class_1id { get; set; }
        public string class_2id { get; set; }
        public string class_3id { get; set; }
        public string class_4id { get; set; }
        public string class_5id { get; set; }
        public decimal? trade_percent_disc { get; set; }
        public string accept_partial_orders { get; set; }
        public decimal? acceptable_wait_time { get; set; }
        public decimal? price_file_id { get; set; }
        public string edi_or_paper { get; set; }
        public string security_info { get; set; }
        public string interchg_receiver_id { get; set; }
        public string intl_san { get; set; }
        public string credit_card_no { get; set; }
        public string credit_card_type { get; set; }
        public string credit_card_name { get; set; }
        public DateTime? credit_card_expiration_date { get; set; }
        public string last_check_number { get; set; }
        public decimal? last_check_amount { get; set; }
        public DateTime? last_check_date { get; set; }
        public string receivable_group_id { get; set; }
        public decimal? credit_limit_per_order { get; set; }
        public string open_item_balance_forward { get; set; }
        public string order_acknowledgments { get; set; }
        public string accept_interchangeable_items { get; set; }
        public string bill_to_contact_id { get; set; }
        public string generate_finance_charges { get; set; }
        public decimal? limit_max_shipments_per_order { get; set; }
        public string credit_limit_check_at_shipment { get; set; }
        public string generate_customer_statements { get; set; }
        public decimal? sic_code { get; set; }
        public decimal? minimum_order_dollar_amount { get; set; }
        public string federal_exemption_number { get; set; }
        public string other_exemption_number { get; set; }
        public string floor_plan_account { get; set; }
        public string default_disposition { get; set; }
        public decimal fc_percentage { get; set; }
        public decimal fc_grace_days { get; set; }
        public decimal minimum_finance_charge { get; set; }
        public string fc_cycle { get; set; }
        public DateTime? last_fc_date { get; set; }
        public string statement_frequency_id { get; set; }
        public decimal? highest_credit_limit_used { get; set; }
        public string billed_on_gross_net_qty { get; set; }
        public string state_excise_tax_exemption_no { get; set; }
        public string credit_status { get; set; }
        public string deferred_revenue_account_no { get; set; }
        public string override_revenue_by_item { get; set; }
        public string pick_ticket_type { get; set; }
        public string finance_chg_revenue_account_no { get; set; }
        public decimal? finance_charge_ship_to_id { get; set; }
        public string customer_name { get; set; }
        public string use_consolidated_invoicing { get; set; }
        public string ci_for_complete_orders_only { get; set; }
        public string ci_print_detail { get; set; }
        public decimal invoice_print_qty { get; set; }
        public string fob_required_flag { get; set; }
        public string cod_required_flag { get; set; }
        public byte? pricing_method_cd { get; set; }
        public int? source_price_cd { get; set; }
        public decimal? multiplier { get; set; }
        public string po_no_required { get; set; }
        public decimal? consolidated_ship_to_id { get; set; }
        public int invoice_batch_uid { get; set; }
        public int? customer_statement_history_uid { get; set; }
        public string trading_partner_name { get; set; }
        public decimal? default_rebate_location_id { get; set; }
        public string lot_bill_summary_on_invoices { get; set; }
        public string print_zero_dollar_customers { get; set; }
        public short generate_statements_by { get; set; }
        public string pending_payment_account_no { get; set; }
        public string print_prices_on_packinglist { get; set; }
        public string job_pricing { get; set; }
        public short? record_type { get; set; }
        public string record_source { get; set; }
        public string slx_contactid { get; set; }
        public int statement_batch_uid { get; set; }
        public string allow_advance_billing { get; set; }
        public string advance_bill_account_no { get; set; }
        public int include_non_alloc_on_pick_tix { get; set; }
        public string exclude_canceld_from_pick_tix { get; set; }
        public string exclude_hold_from_pick_tix { get; set; }
        public string exclude_canceld_from_pack_list { get; set; }
        public string exclude_hold_from_pack_list { get; set; }
        public string exclude_canceld_from_order_ack { get; set; }
        public string exclude_hold_from_order_ack { get; set; }
        public string disp_addl_info_on_invc_flag { get; set; }
        public decimal? remit_to_address_id { get; set; }
        public string default_branch_id { get; set; }
        public int? cust_part_no_group_hdr_uid { get; set; }
        public decimal currency_id { get; set; }
        public string override_profit_limit { get; set; }
        public decimal? minimum_order_line_profit { get; set; }
        public decimal? maximum_order_line_profit { get; set; }
        public decimal? minimum_order_profit { get; set; }
        public decimal? maximum_order_profit { get; set; }
        public DateTime? date_acct_opened { get; set; }
        public string created_by { get; set; }
        public int include_non_alloc_on_pack_list { get; set; }
        public string print_packinglist_in_shipping { get; set; }
        public int? source_type_cd { get; set; }
        public int? pricing_method_cd_web { get; set; }
        public int? source_price_cd_web { get; set; }
        public decimal? multiplier_web { get; set; }
        public string default_orders_to_will_call { get; set; }
        public string send_ucc128info { get; set; }
        public string mfr_no { get; set; }
        public string always_use_job_price { get; set; }
        public string allow_non_job_item { get; set; }
        public string prompt_for_non_job_item { get; set; }
        public string allow_exceed_job_qty { get; set; }
        public string print_lot_attrib_on_invoice { get; set; }
        public string print_lot_attrib_on_packlist { get; set; }
        public int? over_tolerance_percentage { get; set; }
        public int? under_tolerance_percentage { get; set; }
        public int customer_type_cd { get; set; }
        public string lead_source_id { get; set; }
        public int? data_identifier_group_uid { get; set; }
        public string passport_customer_id { get; set; }
        public int? cost_center_tracking_option { get; set; }
        public int fascor_wms_pricing_option { get; set; }
        public string allow_item_level_contract_flag { get; set; }
        public decimal ship_to_credit_limit { get; set; }
        public string legacy_id { get; set; }
        public string parker_customer_cd { get; set; }
        public string web_enabled_flag { get; set; }
        public string allow_line_item_freight_flag { get; set; }
        public int? freight_charge_uid { get; set; }
        public string send_dsc856_flag { get; set; }
        public string pass_through_option_flag { get; set; }
        public string enable_budget_codes_flag { get; set; }
        public string enable_aggregate_budgets_flag { get; set; }
        public int? max_orders_per_budget { get; set; }
        public string service_terms_id { get; set; }
        public decimal downpayment_percentage { get; set; }
        public string req_pymt_upon_release_of_items { get; set; }
        public string include_dp_summary_on_invoices { get; set; }
        public string job_number_required_flag { get; set; }
        public string use_last_margin_pricing_flag { get; set; }
        public int invoice_comp_cost_cd_tier1 { get; set; }
        public decimal? district_id { get; set; }
        public string preferred_flag { get; set; }
        public int? apply_fuel_surcharges_cd { get; set; }
        public string applied_fuelcharges_to_ds_flag { get; set; }
        public string suppress_zero_dollar_flag { get; set; }
        public int invoice_comp_cost_cd_tier2 { get; set; }
        public int invoice_comp_cost_cd_tier3 { get; set; }
        public int? days_until_quote_expires { get; set; }
        public string signature_required_flag { get; set; }
        public int? promise_date_buffer { get; set; }
        public string reclaim_discount_on_memos_flag { get; set; }
        public int? order_surcharge_uid { get; set; }
        public string split_cores_flag { get; set; }
        public DateTime? salesrep_assigned_date { get; set; }
        public string clock_cell_tracking_flag { get; set; }
        public string environmental_fee_flag { get; set; }
        public string admin_fee_flag { get; set; }
        public string epa_cert_on_file_flag { get; set; }
        public int? order_disc_type { get; set; }
        public decimal? order_disc_factor { get; set; }
        public decimal? freight_markup_multiplier { get; set; }
        public string floor_plan_taxable_flag { get; set; }
        public string use_vendor_contracts_flag { get; set; }
        public string pedigree_customer { get; set; }
        public string national_account_flag { get; set; }
        public int? order_priority_uid { get; set; }
        public string manufacturer_distributor_no { get; set; }
        public decimal? manufacturer_program_type_pct { get; set; }
        public string manufacturer_rebate_loc { get; set; }
        public string use_vendor_item_terms_flag { get; set; }
        public string rental_update_flag { get; set; }
        public string foreign_currency_guarantee_type { get; set; }
        public int? sales_market_group_uid { get; set; }
        public string special_labeling_flag { get; set; }
        public string special_packaging_flag { get; set; }
        public string sfdc_account_id { get; set; }
        public DateTime? sfdc_create_date { get; set; }
        public DateTime? sfdc_update_date { get; set; }
        public string use_sys_ups_handling_chrg_flag { get; set; }
        public decimal ups_handling_charge { get; set; }
        public string print_pick_fee_flag { get; set; }
        public string zoom360_grade { get; set; }
        public DateTime? zoom360_grade_expiration_date { get; set; }
        public string price_label_flag { get; set; }
        public string print_complete_orders_flag { get; set; }
        public int? buy_list_hdr_uid { get; set; }
        public int? days_overdue_for_credit_hold { get; set; }
        public int? gl_code_list_hdr_uid { get; set; }
        public string cmi_customer_note { get; set; }
        public string rma_revenue_account_no { get; set; }
        public string so_po_no_required_flag { get; set; }
        public string ar_batch_type { get; set; }
        public string use_int_address_format_flag { get; set; }
        public string gl_code_override_flag { get; set; }
        public string ucc128_form_filename { get; set; }
        public string lowest_across_libraries_flag { get; set; }
        public string price_rounding_flag { get; set; }
        public string dealer_wrrty_claims_account_no { get; set; }
        public string include_aging_info_on_invoice_flag { get; set; }
        public int? decimal_precision_price { get; set; }
        public string private_label_flag { get; set; }
        public string cfn_cost_goods_sold_account { get; set; }
        public string cfn_receivable_account { get; set; }
        public string cfn_revenue_account { get; set; }
        public string servicebench_servicer_no { get; set; }
        public string apply_convenience_fee_flag { get; set; }
        public decimal? default_kit_markup_percent { get; set; }
        public short? fiscal_year_start_month { get; set; }
        public string sales_tax_payable_account_no { get; set; }
        public string customer_tax_class { get; set; }
        public string cons_backorders_flag { get; set; }
        public string servicebench_alt_servicer_no { get; set; }
        public string always_use_eft_payment_flag { get; set; }
        public string eft_validation_sent_flag { get; set; }
        public decimal? scheduled_order_discount { get; set; }
        public decimal? will_call_discount { get; set; }

        public Customer()
        {
            date_created = DateTime.Now;
            created_by = "admin";
            date_last_modified = DateTime.Now;
            last_maintained_by = "admin";
            delete_flag = "N";
            lowest_across_libraries_flag = "N";
        }
    }
}
