using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace P21_latest_template.Models
{
    public class SalesForceOrder
    {
        public string oeh_order_no { get; set; }
        public string oeh_customer_id { get; set; }
        public string oeh_salesrep_id { get; set; }
        public string oeh_order_date { get; set; }
        public string oeh_ship2_name { get; set; }
        public string oeh_ship2_add1 { get; set; }
        public string oeh_ship2_add2 { get; set; }
        public string oeh_ship2_city { get; set; }
        public string oeh_ship2_state { get; set; }
        public string oeh_ship2_zip { get; set; }
        public string oeh_ship2_country { get; set; }
        public string oeh_requested_date { get; set; }
        public string oeh_po_no { get; set; }
        public string oeh_terms { get; set; }
        public string oeh_ship_to_phone { get; set; }
        public string oeh_delete_flag { get; set; }
        public string oeh_completed { get; set; }
        public string oeh_company_id { get; set; }
        public string oeh_date_created { get; set; }
        public string oeh_date_last_modified { get; set; }
        public string oeh_last_maintained_by { get; set; }
        public string oeh_cod_flag { get; set; }
        public string oeh_po_no_append { get; set; }
        public string oeh_location_id { get; set; }
        public string oeh_carrier_id { get; set; }
        public string oeh_address_id { get; set; }
        public string oeh_contact_id { get; set; }
        public string oeh_corp_address_id { get; set; }
        public string oeh_handling_charge_req_flag { get; set; }
        public string oeh_payment_method { get; set; }
        public string oeh_fob_flag { get; set; }
        public string oeh_class_1id { get; set; }
        public string oeh_class_2id { get; set; }
        public string oeh_class_3id { get; set; }
        public string oeh_class_4id { get; set; }
        public string oeh_class_5id { get; set; }
        public string oeh_rma_flag { get; set; }
        public string oeh_taker { get; set; }
        public string oeh_third_party_billing_flag { get; set; }
        public string oeh_approved { get; set; }
        public string oeh_source_location_id { get; set; }
        public string oeh_packing_basis { get; set; }
        public string oeh_delivery_instructions { get; set; }
        public string oeh_pick_ticket_type { get; set; }
        public string oeh_requested_downpayment { get; set; }
        public string oeh_downpayment_invoiced { get; set; }
        public string oeh_cancel_flag { get; set; }
        public string oeh_will_call { get; set; }
        public string oeh_front_counter { get; set; }
        public string oeh_validation_status { get; set; }
        public string oeh_oe_hdr_uid { get; set; }
        public string oeh_credit_card_hold { get; set; }
        public string oeh_freight_out { get; set; }
        public string oeh_exclude_rebates { get; set; }
        public string oeh_job_price_hdr_uid { get; set; }
        public string oeh_front_counter_rma { get; set; }
        public string oeh_ship2_email_address { get; set; }
        public string oeh_order_type { get; set; }
        public string oeh_taxable { get; set; }
        public string oeh_profit_percent { get; set; }
        public string oeh_invoice_exch_rate_source_cd { get; set; }
        public string oeh_rma_expiration_date { get; set; }
        public string oeh_created_by { get; set; }
        public string oeh_invoice_no { get; set; }
        public string oeh_bill_to_contact_id { get; set; }
        public string oeh_tag_hold_cancel_date { get; set; }
        public string oeh_restock_fee_percentage { get; set; }
        public string oeh_date_order_completed { get; set; }
        public string oeh_validated_via_open_orders_flag { get; set; }
        public string oeh_original_promise_date { get; set; }
        public string oeh_promise_date { get; set; }
        public string oeh_requested_ship_date { get; set; }
        public string oeh_expected_completion_date { get; set; }
        public string oeh_job_control_flag { get; set; }
        public string oeh_merchandise_credit_flag { get; set; }
        public string oeh_req_pymt_upon_release_flag { get; set; }
        public string oeh_downpayment_percentage { get; set; }
        public string oeh_prepaid_invoice_flag { get; set; }
        public string oeh_exported_flag { get; set; }
        public string oeh_web_reference_no { get; set; }
        public string oeh_ups_code { get; set; }
        public string oeh_default_pricing_cd { get; set; }
        public string oeh_expedite_date { get; set; }
        public string oeh_environmental_fee_flag { get; set; }
        public string oeh_admin_fee_flag { get; set; }
        public string oeh_promise_date_extended_desc { get; set; }
        public string oeh_promise_date_edited_date { get; set; }
        public string oeh_send_partial_order_flag { get; set; }
        public string oeh_b2b_ups_freight_amount { get; set; }
        public string oeh_user_defined_date { get; set; }
        public string oeh_replace_company_name_flag { get; set; }
        public string oeh_first_packing_list_no { get; set; }
        public string oeh_ship_confirmed_flag { get; set; }
        public string oeh_price_confirmed_flag { get; set; }
        public string oeh_quoted_freight_out { get; set; }
        public string oeh_geocom_append { get; set; }
        public string oeh_apply_fuel_surcharge_flag { get; set; }
        public string oeh_WebOrderID { get; set; }
        public string oeh_override_min_order_charge_flag { get; set; }
        public string oeh_approved_for_ar_flag { get; set; }
        public string oeh_subject { get; set; }
        public string oeh_url { get; set; }
        public string oeh_original_packing_basis { get; set; }
        public string oeh_freight_out_edited_flag { get; set; }
        public string oeh_override_contact_email_flag { get; set; }
        public string oeh_override_email_address { get; set; }
        public string oeh_print_prices_on_packinglist { get; set; }
        public string oeh_web_shopper_id { get; set; }
        public string oeh_web_shopper_email { get; set; }
        public string oeh_limit_max_shipments_per_order { get; set; }
        public string oeh_ship2_add3 { get; set; }
        public string oeh_bill_to_id { get; set; }
        public string oeh_electronic_order_flag { get; set; }
        public string oeh_hold_invoice_flag { get; set; }
        public int Total { get; set; }

        public IEnumerable<SalesForceOrderLine> SFlines { get; set; } = new List<SalesForceOrderLine>();
        public IEnumerable<SalesForceOrderInvoice> SFinvoices { get; set; } = new List<SalesForceOrderInvoice>();
        public IEnumerable<SalesForceOrderShipment> SFshipments { get; set; } = new List<SalesForceOrderShipment>();
    }

    public class SalesForceOrderLine
    {
        public string oel_item_desc { get; set; }
        public string oel_item_id { get; set; }
        public decimal? oel_qty { get; set; }
        public string oel_order_no { get; set; }
        public string oel_unit_price { get; set; }
        public string oel_qty_ordered { get; set; }
        public string oel_qty_per_assembly { get; set; }
        public string oel_company_no { get; set; }
        public string oel_delete_flag { get; set; }
        public string oel_manual_price_overide { get; set; }
        public string oel_date_created { get; set; }
        public string oel_date_last_modified { get; set; }
        public string oel_last_maintained_by { get; set; }
        public string oel_extended_price { get; set; }
        public string oel_sales_tax { get; set; }
        public string oel_line_no { get; set; }
        public string oel_complete { get; set; }
        public string oel_unit_of_measure { get; set; }
        public string oel_base_ut_price { get; set; }
        public string oel_calc_type { get; set; }
        public string oel_calc_value { get; set; }
        public string oel_combinable { get; set; }
        public string oel_disposition { get; set; }
        public string oel_qty_allocated { get; set; }
        public string oel_qty_on_pick_tickets { get; set; }
        public string oel_qty_invoiced { get; set; }
        public string oel_expedite_date { get; set; }
        public string oel_required_date { get; set; }
        public string oel_source_loc_id { get; set; }
        public string oel_ship_loc_id { get; set; }
        public string oel_supplier_id { get; set; }
        public string oel_product_group_id { get; set; }
        public string oel_assembly { get; set; }
        public string oel_scheduled { get; set; }
        public string oel_lot_bill { get; set; }
        public string oel_extended_desc { get; set; }
        public string oel_unit_size { get; set; }
        public string oel_unit_quantity { get; set; }
        public string oel_next_break { get; set; }
        public string oel_next_ut_price { get; set; }
        public string oel_customer_part_number { get; set; }
        public string oel_tax_item { get; set; }
        public string oel_ok_to_interchange { get; set; }
        public string oel_other_charge { get; set; }
        public string oel_sales_cost { get; set; }
        public string oel_commission_cost { get; set; }
        public string oel_requested_downpayment { get; set; }
        public string oel_downpayment_date { get; set; }
        public string oel_will_call { get; set; }
        public string oel_other_cost { get; set; }
        public string oel_downpayment_remaining { get; set; }
        public string oel_cancel_flag { get; set; }
        public string oel_commission_cost_edited { get; set; }
        public string oel_other_cost_edited { get; set; }
        public string oel_po_cost { get; set; }
        public string oel_qty_canceled { get; set; }
        public string oel_pricing_unit { get; set; }
        public string oel_pricing_unit_size { get; set; }
        public string oel_qty_staged { get; set; }
        public string oel_item_source { get; set; }
        public string oel_oe_hdr_uid { get; set; }
        public string oel_parent_oe_line_uid { get; set; }
        public string oel_oe_line_uid { get; set; }
        public string oel_price_page_uid { get; set; }
        public string oel_pricing_option { get; set; }
        public string oel_detail_type { get; set; }
        public string oel_user_line_no { get; set; }
        public string oel_item_terms_discount_pct { get; set; }
        public string oel_default_in_oe { get; set; }
        public string oel_inv_mast_uid { get; set; }
        public string oel_freight_in { get; set; }
        public string oel_substitute_item { get; set; }
        public string oel_allocate_usage_to_original_item { get; set; }
        public string oel_order_cost_edited { get; set; }
        public string oel_pick_date { get; set; }
        public string oel_created_by { get; set; }
        public string oel_original_qty_ordered { get; set; }
        public string oel_disposition_edited_flag { get; set; }
        public string oel_restock_fee_percentage { get; set; }
        public string oel_customer_configured_price { get; set; }
        public string oel_customer_picked_flag { get; set; }
        public string oel_job_price_line_uid { get; set; }
        public string oel_cust_po_no { get; set; }
        public string oel_use_contract_cost { get; set; }
        public string oel_cost_price_page_uid { get; set; }
        public string oel_ud_cost { get; set; }
        public string oel_item_bill_to_id { get; set; }
        public string oel_buyback_no { get; set; }
        public string oel_additional_description { get; set; }
        public string oel_bill_hold_flag { get; set; }
        public string oel_clock { get; set; }
        public string oel_cell { get; set; }
        public string oel_environmental_fee { get; set; }
        public string oel_admin_fee { get; set; }
        public string oel_core_price { get; set; }
        public string oel_ext_disc_amt { get; set; }
        public string oel_system_calc_unit_price { get; set; }
        public string oel_buyer { get; set; }
        public string oel_recipient { get; set; }
        public string oel_original_unit_price { get; set; }
        public string oel_quote_price_oe_line_uid { get; set; }
        public string oel_price1 { get; set; }
        public string oel_retail_price { get; set; }
        public string oel_sales_discount_group_id { get; set; }
        public string oel_price_family_uid { get; set; }
        public string oel_competitor_uid { get; set; }
        public string oel_price_adj_note { get; set; }
        public string oel_rfq_indicator_flag { get; set; }
        public string oel_buy_get_rewards_flag { get; set; }
        public string oel_buy_get_x_rewards_program_uid { get; set; }
        public string oel_carrier_rebate_cost { get; set; }
        public string oel_line_discount { get; set; }
        public string oel_line_discount_description { get; set; }
        public string oel_extended_desc_location { get; set; }
        public string oel_extended_desc_customer { get; set; }
        public string oel_eco_fee_amount { get; set; }
        public string oel_generic_custom_description { get; set; }
        public string oel_line_seq_no { get; set; }
        public string oel_secondary_unit_price { get; set; }
        public string oel_secondary_extended_price { get; set; }
        public string oel_secondary_manual_price_overide { get; set; }
        public string oel_currentbin_uid { get; set; }
        public string oel_qa_status { get; set; }
        public string oel_prediscount_unit_price { get; set; }
        public string oel_cust_percentage_disc { get; set; }
        public string oel_original_qty_allocated { get; set; }
    }

    public class SalesForceOrderInvoice
    {
        public string ih_invoice_no { get; set; }
        public string ih_order_no { get; set; }
        public string ih_order_date { get; set; }
        public string ih_invoice_date { get; set; }
        public string ih_customer_id { get; set; }
        public string ih_bill2_name { get; set; }
        public string ih_bill2_contact { get; set; }
        public string ih_bill2_address1 { get; set; }
        public string ih_bill2_address2 { get; set; }
        public string ih_bill2_city { get; set; }
        public string ih_bill2_state { get; set; }
        public string ih_bill2_postal_code { get; set; }
        public string ih_ship2_name { get; set; }
        public string ih_ship2_contact { get; set; }
        public string ih_ship2_address1 { get; set; }
        public string ih_ship2_address2 { get; set; }
        public string ih_ship2_city { get; set; }
        public string ih_ship2_state { get; set; }
        public string ih_ship2_postal_code { get; set; }
        public string ih_carrier_name { get; set; }
        public string ih_fob { get; set; }
        public string ih_terms_desc { get; set; }
        public string ih_po_no { get; set; }
        public string ih_salesrep_id { get; set; }
        public string ih_salesrep_name { get; set; }
        public string ih_brokerage { get; set; }
        public string ih_freight { get; set; }
        public string ih_ar_account_no { get; set; }
        public string ih_gl_freight_account_no { get; set; }
        public string ih_gl_brokerage_account_no { get; set; }
        public string ih_brokerage_amt { get; set; }
        public string ih_period { get; set; }
        public string ih_year_for_period { get; set; }
        public string ih_store_no { get; set; }
        public string ih_invoice_type { get; set; }
        public string ih_ship_to_id { get; set; }
        public string ih_ship_date { get; set; }
        public string ih_total_amount { get; set; }
        public string ih_amount_paid { get; set; }
        public string ih_terms_taken { get; set; }
        public string ih_allowed { get; set; }
        public string ih_paid_in_full_flag { get; set; }
        public string ih_date_paid { get; set; }
        public string ih_print_flag { get; set; }
        public string ih_print_date { get; set; }
        public string ih_company_no { get; set; }
        public string ih_customer_id_number { get; set; }
        public string ih_date_created { get; set; }
        public string ih_date_last_modified { get; set; }
        public string ih_last_maintained_by { get; set; }
        public string ih_printed { get; set; }
        public string ih_printed_date { get; set; }
        public string ih_corp_address_id { get; set; }
        public string ih_shipping_cost { get; set; }
        public string ih_bill2_country { get; set; }
        public string ih_ship2_country { get; set; }
        public string ih_invoice_reference_no { get; set; }
        public string ih_invoice_desc { get; set; }
        public string ih_memo_amount { get; set; }
        public string ih_bad_debt_amount { get; set; }
        public string ih_invoice_class { get; set; }
        public string ih_period_fully_paid { get; set; }
        public string ih_year_fully_paid { get; set; }
        public string ih_approved { get; set; }
        public string ih_net_due_date { get; set; }
        public string ih_terms_due_date { get; set; }
        public string ih_terms_id { get; set; }
        public string ih_branch_id { get; set; }
        public string ih_disputed_flag { get; set; }
        public string ih_other_charge_amount { get; set; }
        public string ih_tax_amount { get; set; }
        public string ih_sold_to_ah_uid { get; set; }
        public string ih_sold_to_customer_id { get; set; }
        public string ih_ship_to_phone { get; set; }
        public string ih_terms_amount { get; set; }
        public string ih_sales_location_id { get; set; }
        public string ih_ship2_email_address { get; set; }
        public string ih_created_by { get; set; }
        public string ih_job_id { get; set; }
        public string ih_invoice_paid_period { get; set; }
        public string ih_invoice_period { get; set; }
        public string ih_commission_cost { get; set; }
        public string ih_external_reference_no { get; set; }
        public string ih_total_freightcharge_weight { get; set; }
        public string ih_receiver_name { get; set; }
        public string ih_downpayment_applied { get; set; }
        public string ih_update_tracking { get; set; }
        public string ih_sent_to_carrier_date { get; set; }
        public string ih_tax_terms_amt { get; set; }
        public string ih_tax_amount_paid { get; set; }
        public string ih_bill2_address3 { get; set; }
        public string ih_ship2_address3 { get; set; }
        public string ih_iva_withheld_amount { get; set; }
        public string ih_carrier_id { get; set; }
        public string ih_free_out_freight_min_met_flag { get; set; }
        public string ih_ship2_latitude { get; set; }
        public string ih_ship2_longitude { get; set; }
        public string ih_bill_to_supplier_flag { get; set; }
        public string ih_actual_freight_cost { get; set; }
        public string ih_eco_fee_amt { get; set; }
        public string ih_frght_disc_taken { get; set; }
        public IEnumerable<SalesForceOrderInvoiceLine> items { get; set; } = new List<SalesForceOrderInvoiceLine>();
    }

    public class SalesForceOrderInvoiceLine
    {
        public string il_item_id { get; set; }
        public decimal? il_qty { get; set; }
        public string il_invoice_no { get; set; }
        public string il_qty_requested { get; set; }
        public string il_qty_shipped { get; set; }
        public string il_unit_of_measure { get; set; }
        public string il_item_desc { get; set; }
        public string il_unit_price { get; set; }
        public string il_extended_price { get; set; }
        public string il_date_created { get; set; }
        public string il_date_last_modified { get; set; }
        public string il_last_maintained_by { get; set; }
        public string il_order_no { get; set; }
        public string il_cogs_amount { get; set; }
        public string il_job_id { get; set; }
        public string il_customer_part_number { get; set; }
        public string il_company_id { get; set; }
        public string il_tax_item { get; set; }
        public string il_pricing_quantity { get; set; }
        public string il_net_quantity { get; set; }
        public string il_line_no { get; set; }
        public string il_sales_cost { get; set; }
        public string il_commission_cost { get; set; }
        public string il_other_cost { get; set; }
        public string il_oe_line_number { get; set; }
        public string il_other_charge_item { get; set; }
        public string il_exceptional_sales { get; set; }
        public string il_pricing_unit { get; set; }
        public string il_invoice_line_uid { get; set; }
        public string il_invoice_line_uid_parent { get; set; }
        public string il_inv_mast_uid { get; set; }
        public string il_invoice_line_type { get; set; }
        public string il_product_group_id { get; set; }
        public string il_supplier_id { get; set; }
        public string il_created_by { get; set; }
        public string il_job_price_line_uid { get; set; }
        public string il_customer_contract_uid { get; set; }
        public string il_one_time_price_flag { get; set; }
        public string il_environmental_fee { get; set; }
        public string il_admin_fee { get; set; }
        public string il_core_price { get; set; }
        public string il_covered_extended_price { get; set; }
        public string il_cost_price_page_uid { get; set; }
        public string il_buyer { get; set; }
        public string il_recipient { get; set; }
        public string il_verified_flag { get; set; }
        public string il_processed_flag { get; set; }
        public string il_cogs_markup_amount { get; set; }
        public string il_sales_discount_group_id { get; set; }
        public string il_price_family_uid { get; set; }
        public string il_sent_to_carrier_date { get; set; }
        public string il_discount_item_flag { get; set; }
        public string il_other_charge_credit_rebill_flag { get; set; }
        public string il_sub_invoice_no { get; set; }
    }

    public class SalesForceOrderShipment
    {
        public decimal? pick_ticket_no { get; set; }
        public decimal? carrier_code { get; set; }
        public string title { get; set; }
        public string tracking_number { get; set; }
        public IEnumerable<SalesForceOrderShipmentLine> items { get; set; } = new List<SalesForceOrderShipmentLine>();
    }

    public class SalesForceOrderShipmentLine
    {
        public decimal? pick_ticket_no { get; set; }
        public decimal qty { get; set; }
        public string item_id { get; set; }
    }

    public class SalesForceOrderPickTicket
    {
        public decimal pick_ticket_no { get; set; }
        public string company_id { get; set; }
        public decimal? carrier_id { get; set; }
        public string carrier_name { get; set; }
        public string tracking_no { get; set; }
    }
}
